---
title: "Figure 3"
author: "Lambda Moses"
date: "11/19/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
devtools::load_all("~/museumst/")
library(tidyverse)
library(patchwork)
library(gganatogram)
theme_set(theme_bw())
```

```{r}
nms <- c("Prequel", "Microdissection", "smFISH", "Array", "ISS", "No imaging")
data_sheets <- read_metadata(nms, update = TRUE)
```

```{r}
data_sheets <- data_sheets %>% 
  mutate(era = case_when(sheet == "Prequel" ~ "prequel",
                         TRUE ~ "current"))
```

```{r}
publications <- get_pubs_df(data_sheets, "era")
```

```{r}
methods_current <- data_sheets %>% 
  select(title, date_published, method, sheet, era, country:short_name) %>% 
  filter(era == "current", !is.na(method)) %>% 
  distinct()
```

```{r}
(p3a <- methods_current %>% 
   select(institution, method) %>% 
   distinct() %>% 
   mutate(method = fct_lump_min(method, 3)) %>% 
   filter(!method %in% c("LCM", "Other")) %>% 
   pubs_per_cat(method) +
   labs(y = "Number of institutions", x = "Technology"))
```

```{r}
smfish <- read_metadata("smFISH", update = TRUE)
```

```{r}
mean_genes <- smfish %>% 
  group_by(date_published, title, method) %>% 
  summarize(n_genes = mean(n_genes, na.rm = TRUE))
```

```{r}
(p3c <- mean_genes %>% 
  filter(n_genes < 1500) %>% 
  ggplot(aes(date_published, n_genes)) +
  geom_point(aes(color = method)) +
  geom_text_repel(aes(label = method, color = method), segment.alpha = 0.5) +
  geom_smooth(method = "lm") +
  labs(x = "Date published", title = "Mean number of genes per study per technique",
       y = NULL) +
  theme(legend.position = "none"))
```

```{r}
sum_cells <- smfish %>% 
  group_by(date_published, title, method) %>% 
  summarize(n_cells = sum(`n_cells/bins/spots`, na.rm = TRUE)) %>% 
  filter(n_cells > 0)
```

```{r}
sum_cells2 <- sum_cells %>% 
  filter(n_cells < 1e5)
(p3d <- ggplot(sum_cells2, aes(date_published, n_cells)) +
  geom_point(aes(color = method)) +
  geom_text_repel(aes(label = method, color = method), segment.alpha = 0.5) +
  geom_smooth(method = "lm") +
  labs(x = "Date published", title = "Total number of cells per study", y = NULL) +
  theme(legend.position = "none") +
  coord_cartesian(ylim = c(0, max(sum_cells2$n_cells))))
```

```{r}
species <- data_sheets %>%
  filter(era == "current", !is.na(species)) %>% 
  unnest_cat(species)
```

```{r}
data("species_cols")
```

```{r}
species_pie <- species %>% 
  mutate(species = fct_lump(species, 3)) %>% 
  count(species) %>% 
  mutate(species = fct_reorder(species, n, .desc = TRUE) %>% 
           fct_relevel("Other", after = Inf)) %>% 
  arrange(desc(species)) %>% 
  mutate(label = paste("italic('", species, "')", "~(", n, ")"))
```

```{r}
(p3e <- ggplot(species_pie, aes(x = "", y = n, fill = species)) +
   geom_col(position = "stack", color = "gray50", size = 0.3, show.legend = FALSE,
            width = 1) +
   geom_text_repel(aes(x = 1.5, label = label), parse = TRUE, segment.size = 0,
                   position = position_stack(vjust = 0.5)) +
   coord_polar(theta = "y") +
   scale_fill_manual(values = species_cols) +
   scale_y_continuous(breaks = species_pie$y_label, labels = species_pie$label) +
   scale_x_discrete(expand = expansion(0.1)) +
   theme_void()
   )
```

```{r}
data("hgFemale_key")
data("mmFemale_key")
data("hgMale_key")
```

```{r}
organs <- data_sheets %>% 
  filter(era == "current") %>% 
  select(date_published:journal, country:year, species, sheet, organ, pathological) %>% 
  distinct()
organs <- organs %>% 
  filter(species %in% c("Mus musculus", "Homo sapiens")) %>% 
  unnest_cat(organ, other_cols = c("species", "pathological")) %>% 
  filter(!is.na(organ))
```

```{r}
organs_hg_f <- organs %>% 
  filter(species == "Homo sapiens") %>% 
  inner_join(hgFemale_key[, c("organ", "type")], by = "organ") %>% 
  count(organ, type, pathological, name = "value")
```

```{r}
organs_mm_f <- organs %>% 
  filter(species == "Mus musculus") %>% 
  inner_join(mmFemale_key[, c("organ", "type")], by = "organ") %>% 
  count(organ, type, pathological, name = "value")
```

```{r}
organs_hg_m <- organs %>% 
  filter(species == "Homo sapiens") %>% 
  inner_join(hgMale_key[, c("organ", "type")], by = "organ") %>% 
  count(organ, type, pathological, name = "value")
```

Use the same color scale across humans and mice
```{r}
limits_use <- range(c(organs_hg_f$value[!organs_hg_f$pathological], 
                      organs_mm_f$value[!organs_mm_f$pathological]))
```

```{r}
(p3f <- organs_hg_m %>% 
   filter(!pathological) %>% 
   gganatogram(organism = "human", sex = "male", fill = "value") +
   coord_equal() +
   theme_void() +
   scale_fill_distiller(palette = "Blues", direction = 1, name = "# publications\n(healthy)",
                        limits = limits_use))
```

```{r}
limits_use2 <- range(c(organs_hg_f$value[organs_hg_f$pathological],
                       organs_mm_f$value[organs_mm_f$pathological]))
```

```{r}
(p3g <- organs_hg_f %>% 
   filter(pathological) %>% 
   gganatogram(organism = "human", sex = "female", fill = "value") +
   coord_equal() +
   theme_void() +
   scale_fill_distiller(palette = "Reds", direction = 1, name = "# publications\n(pathological)",
                        limits = limits_use2, breaks = breaks_width(2)))
```

```{r}
(p3h <- organs_mm_f %>% 
   filter(!pathological) %>% 
   gganatogram(organism = "mouse", sex = "female", fill = "value") +
   coord_equal() +
   theme_void() +
   scale_fill_distiller(palette = "Blues", direction = 1, name = "# publications\n(healthy)",
                        limits = limits_use))
```

```{r}
(p3i <- organs_mm_f %>% 
   filter(pathological) %>% 
   gganatogram(organism = "mouse", sex = "female", fill = "value") +
   coord_equal() +
   theme_void() +
   scale_fill_distiller(palette = "Reds", direction = 1, name = "# publications\n(pathological)",
                        limits = limits_use2, breaks = breaks_width(2)))
```

```{r}
# prequel sheet doesn't have programming language information anyway though it has that columnn
langs <- unnest_cat(data_sheets, language)
```

```{r}
(p3j <- pubs_per_cat(langs, language, n_top = 5, isotype = TRUE, img_unit = 10) +
  labs(title = "Users (downstream analysis)"))
```
```{r}
analysis <- read_metadata("Analysis", update = TRUE)
```

```{r}
langs %>% 
  count(language) %>% 
  arrange(desc(n))
```

```{r}
analysis_langs <- unnest_cat(analysis, language, 
                             other_cols = c("documented", "CRAN/Bioc/pip/conda"))
```

```{r}
(p3k <- pubs_per_cat(analysis_langs, language, n_top = 5, isotype = TRUE, img_unit = 10) +
  scale_y_continuous(limits = c(0, 99), 
                     breaks = seq(0, 100, by = 20),
                     expand = expansion(mult = c(0, 0.05))) +
  labs(title = "Package developers"))
```

```{r, fig.width=8, fig.height=8}
fig3_top <- wrap_elements(full = p3a) + p3f + p3g +
  p3e + p3h + p3i +
  plot_layout(ncol = 3, guides = "collect", widths = c(1.8, 1, 1), heights = c(1.3, 1))
fig3_bottom <- p3c + p3d +
  p3j + p3k +
  plot_layout(ncol = 2)
(fig3 <- fig3_top / fig3_bottom +
    plot_layout(heights = c(1.3, 1)) +
    plot_annotation(tag_levels = "A"))
```

```{r}
ggsave("fig3.png", fig3, width = 12, height = 14)
```

