---
title: "Figure 1"
author: "Lambda Moses"
date: "11/9/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Code to make Figure 1
```{r}
library(museumst)
library(patchwork)
library(tidyverse)
```

```{r}
events <- read_major_events(update = TRUE)
```

```{r, fig.width=8, fig.height=3}
(p1a <- events %>% 
  filter(category == "technique") %>% 
  plot_timeline(c(1.5, -1.5, 1, -1.5, 1, -1.5, 2, -2.5, 1.2),
                expand_x = c(0.1, 0.1), expand_y = c(0,0)) +
   ggtitle("Major events in evolution of prequel techniques"))
```

```{r, fig.width=8, fig.height=4}
(p1b <- events %>% 
  filter(category == "ISH atlas") %>% 
  plot_timeline(c(0.5, -0.5, -0.85, 0.7, -0.25, 1, -0.5, 0.3, -0.8, 0.5, -1, 0.7, -0.25, 0.5, 
                  -0.87, 1, -0.6, 0.3, -0.5, 0.3), description_width = 25,
                expand_x = c(0.1, 0.1), expand_y = c(0,0)) +
   ggtitle("Major prequel (WM)ISH atlases"))
```

```{r, fig.width=8, fig.height=4}
(p1c <- events %>% 
  filter(category == "technique2") %>% 
  plot_timeline(c(-0.5, 0.5, -0.5, -1, 0.5, 0.7, -0.8, -0.3, -0.6, 0.5, -0.5,
                  0.6, 1, -0.6, 0.3, -1, -0.3), 
                expand_y = c(0,0), expand_x = c(0.1,0.1)) +
   ggtitle("Major events in evolution of current era techniques"))
```

```{r, fig.width=8, fig.height=12}
(fig1 <- p1a + p1b + p1c +
   plot_layout(ncol = 1, guides = "collect", heights = c(1, 1.35, 1)) +
   plot_annotation(tag_levels = "A") &
   theme(legend.position = "bottom", legend.title = element_blank(), 
         legend.spacing = unit(0, "lines")))
```

```{r}
ggsave("fig1.pdf", fig1, width = 12, height = 13)
```

```{r}
sessionInfo()
```

